In [12]:
import numpy as np

Array de una dimensión

In [8]:
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


Array de dos dimensiones

In [9]:
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


Array de tres dimensiones

In [10]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


Atributos de un array
* a.ndim: Devuelve el número de dimensiones del array a.
* a.shape: Devuelve una tupla con las dimensiones del array a.
* a.size: Devuelve el número de elementos del array a.
* a.dt

<class 'TypeError'>: Cannot interpret '2' as a data type

In [14]:
print(np.idendity(3))

<class 'AttributeError'>: module 'numpy' has no attribute 'idendity'